name: ascot-env
channels:
  - conda-forge
dependencies:
  - c-compiler
  - make
  - llvm-openmp
  - python>=3.10,<3.14
  - hdf5
  - zlib
  - setuptools
  - pip
  - ipython
  - numpy
  - scipy
  - h5py
  - xmlschema
  - unyt
  - wurlitzer
  - matplotlib
  - pyvista
  - freeqdsk
  - gsl
  - xarray
  - lmfit
